# Generated by Django 5.2.1 on 2025-06-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0018_alter_carad_brand_alter_carad_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carad',
            name='seats_num',
            field=models.PositiveIntegerField(null=True, verbose_name='Мест'),
        ),
    ]
